[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "I", "F", "UP", "SIM", "B"]
ignore = ["E741"]
task-tags = ["TODO", "FIXME", "HACK", "XXX"]


[tool.ruff.format]
quote-style = "double"  # Optional: Use double quotes

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"
