name: Run Tests

on:
  push:
    branches-ignore:
      - main  # Ignore direct pushes to main
  pull_request:
    branches:
      - main  # Run on PRs targeting main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true  # Ignore if no requirements.txt

      - name: Run Pytest
        run: |
          pytest tests --disable-warnings